import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test("desktop services, keyboard tabs, links and accessibility", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/");
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Clear next steps");
  await expect(page.getByRole("tab")).toHaveCount(6);
  await expect(page.getByRole("tabpanel")).toHaveCount(1);
  await page.getByRole("tab").first().focus();
  await page.keyboard.press("End");
  await expect(page.getByRole("tab").last()).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("tabpanel")).toContainText("Stronger foundations");
  await page.keyboard.press("Home");
  await expect(page.getByRole("tab").first()).toBeFocused();
  await page.screenshot({ path: "test-results/home-desktop.png", fullPage: true });
  const audit = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze();
  expect(audit.violations).toEqual([]);
  expect(errors).toEqual([]);
});

test("mobile navigation, no overflow, FAQ, discovery review and disabled sending", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const menu = page.getByRole("button", { name: "Open navigation" });
  await menu.click();
  await expect(page.getByRole("navigation", { name: "Mobile navigation" })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(menu).toBeFocused();
  await expect(page.getByRole("navigation", { name: "Mobile navigation" })).toBeHidden();
  await page.locator("summary").first().click();
  await expect(page.locator("details").first()).toHaveAttribute("open", "");
  await page.screenshot({ path: "test-results/home-mobile.png", fullPage: true });
  await page.goto("/project-discovery?service=data");
  await expect(page.getByLabel("Data analytics & business intelligence", { exact: true })).toBeChecked();
  await page.getByLabel("Tell us about your project").fill("We need clearer reporting for our operations team.");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByLabel("Your name", { exact: true }).fill("Test Visitor");
  await page.getByLabel("Email address", { exact: true }).fill("visitor@example.test");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Does everything look right?" })).toBeFocused();
  await page.getByRole("button", { name: "Edit project", exact: true }).click();
  await expect(page.getByLabel("Tell us about your project")).toHaveValue("We need clearer reporting for our operations team.");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await expect(page.getByLabel("Your name", { exact: true })).toHaveValue("Test Visitor");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Send enquiry", exact: true }).click();
  await expect(page.locator(".form-panel").getByRole("alert")).toContainText("has not been sent");
  await page.screenshot({ path: "test-results/discovery-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
  const response = await page.request.post("/api/inquiries", { data: {} });
  expect(response.status()).toBe(503);
  await page.goto("/privacy");
  await expect(page.getByRole("heading", { level: 1 })).toContainText("privacy notice");
});
