import Link from "next/link";
import { StaffStats } from "@/components/staff-stats";
import { ArrowRight, Search } from "lucide-react";
import { previewInquiries, type PreviewStatus } from "@/lib/staff-preview";
import { services } from "@/lib/services";

const statuses: PreviewStatus[] = ["New", "Contacted", "Proposal Sent"];
function StatusBadge({ status }: { status: PreviewStatus }) { const symbol = status === "New" ? "●" : status === "Contacted" ? "✓" : "→"; return <span className={`status-badge status-${status.toLowerCase().replaceAll(" ", "-")}`}><span aria-hidden="true">{symbol}</span>{status}</span>; }

export default async function StaffPreviewPage({ searchParams }: PageProps<"/admin/preview">) {
  const params = await searchParams;
  const status = typeof params.status === "string" && statuses.includes(params.status as PreviewStatus) ? params.status as PreviewStatus : undefined;
  const search = typeof params.q === "string" ? params.q.trim().slice(0, 100) : "";
  const searchLower = search.toLowerCase();
  const inquiries = previewInquiries.filter((inquiry) => (!status || inquiry.status === status) && (!searchLower || [inquiry.reference, inquiry.name, inquiry.company, inquiry.email].some((value) => value?.toLowerCase().includes(searchLower))));
  const filterHref = (nextStatus?: PreviewStatus) => `/admin/preview?${new URLSearchParams({ ...(nextStatus ? { status: nextStatus } : {}), ...(search ? { q: search } : {}) })}`;

  return <div className="staff-workspace"><header className="staff-page-header"><div><span className="eyebrow purple">Innomarks operations</span><h1>Project inquiries</h1><p>Review incoming project briefs and keep track of each inquiry.</p></div></header><StaffStats basePath="/admin/preview" counts={{ total: previewInquiries.length, new: previewInquiries.filter(i => i.status === "New").length, contacted: previewInquiries.filter(i => i.status === "Contacted").length, proposals: previewInquiries.filter(i => i.status === "Proposal Sent").length }} /><nav className="summary-filters" aria-label="Filter preview inquiries"><Link className={!status ? "active" : ""} href={filterHref()}>All inquiries <b>{previewInquiries.length}</b></Link>{statuses.map((item) => <Link key={item} className={status === item ? "active" : ""} href={filterHref(item)}>{item} <b>{previewInquiries.filter((inquiry) => inquiry.status === item).length}</b></Link>)}</nav><form className="lead-toolbar" role="search"><label htmlFor="preview-search" className="sr-only">Search preview inquiries</label><Search size={17} aria-hidden="true" /><input id="preview-search" name="q" placeholder="Search inquiries..." defaultValue={search} />{status && <input type="hidden" name="status" value={status} />}<button type="submit">Search</button></form>{!inquiries.length ? <div className="staff-state"><h2>No inquiries match your search.</h2><p><Link href="/admin/preview">Clear search and filters</Link></p></div> : <><div className="lead-table-wrap"><table className="lead-table"><thead><tr><th>Client / lead</th><th>Service</th><th>Budget</th><th>Status</th><th>Received</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{inquiries.map((inquiry) => <tr key={inquiry.id}><td><strong>{inquiry.company || inquiry.name}</strong>{inquiry.company && <small>{inquiry.name}</small>}</td><td>{services.filter((service) => inquiry.serviceIds.includes(service.id)).map((service) => service.shortName).join(", ")}</td><td>{inquiry.budget}</td><td><StatusBadge status={inquiry.status} /></td><td><time dateTime={inquiry.receivedAt}>{new Intl.DateTimeFormat("en-ZA", { timeZone: "Africa/Johannesburg", dateStyle: "medium" }).format(new Date(inquiry.receivedAt))}</time></td><td><Link aria-label={`View ${inquiry.reference}`} href={`/admin/preview/${inquiry.id}`}><ArrowRight size={17} aria-hidden="true" /></Link></td></tr>)}</tbody></table></div><div className="lead-cards">{inquiries.map((inquiry) => <article key={inquiry.id}><StatusBadge status={inquiry.status} /><h2>{inquiry.company || inquiry.name}</h2>{inquiry.company && <p>{inquiry.name}</p>}<dl><div><dt>Budget</dt><dd>{inquiry.budget}</dd></div></dl><Link href={`/admin/preview/${inquiry.id}`}>View inquiry <ArrowRight size={16} aria-hidden="true" /></Link></article>)}</div></>}</div>;
}
